# -*- coding: utf-8 -*-
"""KRecommender_past_question.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gsQpHQkbK2_-4NhPIbZIBtEvJnjs_JCS
"""

pip install krecommend==0.0.2

from krecommend.recommend import KRecommend
import pandas as pd
import numpy as np

file=pd.read_csv("/content/drive/MyDrive/pq_file/past_question_file.csv")

#get text_columns
text_columns=[]
for column in file.columns:
  if file[column].dtype=="object":
    text_columns.append(column)

#convert and add examyear to text_columns
file["examyear"]=file["examyear"].astype("O")
text_columns.append("examyear")

file

file.dtypes

text_columns=["question","option_a","option_b","option_c","option_d","section","answer","examtype"]

recommender=KRecommend(k=4)

recommender.fit(file,text_columns)

index=100
question=file["question"].iloc[index]
option_a=file["option_a"].iloc[index]
option_b=file["option_b"].iloc[index]
option_c=file["option_c"].iloc[index]
option_d=file["option_d"].iloc[index]
section=file["section"].iloc[index]
answer=file["answer"].iloc[index]
examtype=file["examtype"].iloc[index]

recommendations=recommender.predict([question,option_a,option_b,option_c,option_d,section,answer,examtype])

recommendations

recommendation_list=[]
for index in recommendations.keys():
  recommendation_list.append(file.iloc[index])

recommendation_list